### ISSUE TITLE
date always goes one day prior to selected date

### ISSUE THREAD

**Issue by jm355** [thatsmanmeet/Tasky#108] opened 2024-08-07 13:13 UTC
Watch the dates selected and displayed in this screen record. They are always the day prior. So if I select the 7th, it displays the 6th

https://github.com/user-attachments/assets/5e82eac5-9530-4478-95e1-3c4fa97441dd

**Comment by thatsmanmeet** [comment] 2024-08-07 13:22
can you confirm that this issue is only happening with material date picker by toggling legacy pickers in settings or it's issue on both pickers.

**Comment by jm355** [comment] 2024-08-07 13:38
The issue is not present when I use the legacy picker

**Comment by thatsmanmeet** [comment] 2024-08-07 13:42
Ok, so problem seems to be in new material 3 pickers. I'll release fix in next release. Till then you can use legacy pickers for the time being.

**Comment by thatsmanmeet** [comment] 2024-08-07 13:59
I'm unable to reproduce this bug on my end. I have checked on two different devices and picker seems to work fine. I'll try to reproduce this bug and wait for some more users to report this issue before I can work on resolving the issue. Till then you can use legacy pickers.

[Screen_recording_20240807_192305.webm](https://github.com/user-attachments/assets/29cf586d-53ee-4617-8f35-e88ec28ce1a8)

**Comment by jm355** [comment] 2024-08-07 17:39
Interesting. The only difference I see between your recording and mine is that I have a time set. Maybe that has something to do with it?

**Comment by thatsmanmeet** [comment] 2024-08-08 06:16
Well, time picker is independent of date picker, so that shouldn't really cause any problem. I'll wait until I can reproduce this issue or someone else also reports the same issue here before I look into this issue since the code seems to work fine! Till then maybe you can try synchronizing date and time in your phone settings to see if that fixes the issue or not. It could be that system have some type of date/time synchronization bug with the app's material picker since legacy picker works fine.

**Closed** 2024-08-18 12:26 UTC
Labels: more info needed

**Comment by ColombiniP** [comment] 2024-08-20 00:40
Baixei o app hoje e tenho mesmo problema que o do amigo jm355, quando seleciono a data para a tarefa, ela fica com um dia de atraso, no dia anterior. Usando o legado isso não ocorre, segue o vídeo da tela.

I downloaded the app today and I have the same problem as my friend jm355, when I select the date for the task, it is one day late, the day before. Using legacy this does not happen, follow the screen video.

https://github.com/user-attachments/assets/8d893b5b-025d-473b-a338-4c113a3964c7
